import AuthProvider from '@/components/AuthProvider'
import '../globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthProvider>
          <main className='h-full bg-gray-900 flex justify-center items-center flex-col'>
            <div className='bg-gray-800 rounded-lg p-10 shadow-sm shadow-black'>
              {children}
            </div>
          </main>
        </AuthProvider>
      </body>
    </html>
  )
}
