import Navbar from '@/components/Navbar'
import '../globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { PokemonDisplay } from '@/components/PokemonDisplay'
import AuthProvider from '@/components/AuthProvider'
import { IPokemon } from '@/types/models/Pokemon'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  return (
    <html lang="en">
      <body className={`${inter.className} bg-gray-900 flex flex-col`}>
        <AuthProvider>
          <main className='flex flex-1 overflow-y-scroll flex-col items-center gap-4 pb-8'>
            <PokemonDisplay />
            {children}
          </main>
          <Navbar />
        </AuthProvider>
      </body>
    </html>
  )
}
